# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-24 17:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('descripcion', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('breveDescripcion', models.CharField(max_length=300)),
                ('parrafo1', models.CharField(max_length=1000)),
                ('parrafo2', models.CharField(blank=True, max_length=1000, null=True)),
                ('parrafo3', models.CharField(blank=True, max_length=1000, null=True)),
                ('parrafo4', models.CharField(blank=True, max_length=1000, null=True)),
                ('parrafo5', models.CharField(blank=True, max_length=1000, null=True)),
                ('parrafo6', models.CharField(blank=True, max_length=1000, null=True)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('fuente', models.CharField(max_length=300)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='noticias/static/photos/%Y/%m/%d')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='noticia',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noticias.Seccion'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='noticia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Comentarios', to='noticias.Noticia'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
