# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-25 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0003_auto_20170125_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seccion',
            name='tipo',
            field=models.CharField(max_length=100),
        ),
    ]
